public enum ResponseCode {
    USER_AUTHORIZED,
    USER_ADDED,
    USER_NOT_ADDED,
    USER_DISCONNECTED,
    USER_NOT_FOUND,
    PRODUCT_ADDED,
    PRODUCT_NOT_ADDED,
    PURCHASE_COMPLETE,
    PURCHASE_NOT_COMPLETE
}
